#ifndef ADC1_CONFIG_H
#define ADC1_CONFIG_H

#include "Std_Types.h"

#define 	SINGLE_CHANNEL_MODE				0x0U
#define 	SINGLE_CH_CONTINOUS_CONV		0x1U
#define 	REGULAR_CHS_SINLGE_CONV			0x2U
#define 	REGULAR_CHS_CONTINOUS_CONV		0x3U



#define 	ADC1_MODE		SINGLE_CH_SINGLE_CONV





#endif
